# Disable implict rules with "make -r"

TARGET = memory 
CC = gcc
CFLAGS = -Wall -ggdb #enable warnings and debugging info
LDFLAGS = # here we could add dynamically linked libraries like -lrt -lm -lpthread and others

# here we list all source files
SRC = memory.c bits.c threads.c
OBJS = $(SRC:.c=.o)
DEPS = $(OBJS:.o=.d)
DSYM = $(OBJS:.o=.dSYM)

.PHONY: all clean

all: $(TARGET)

# let's clean up the mess
clean:
	rm -f $(TARGET) $(OBJS) $(DEPS); 
	rm -rf $(DSYM)

memory: memory.o bits.o
	$(CC) $^ $(LDFLAGS) -o $@

%: %.o lib%.so
	$(CC) $^ $(LDFLAGS) -shared -o $@


# the -MMD flags creates dependency files for every object, so 
%.o: %.c
	$(CC) $(CFLAGS) -c -fpic -MMD $<  


# here make reads the dependency files and handle them.
-include $(DEPS)

